name: Good Reads
favicon: null
layout_spectrum: 0.5254762768745422
typography_spectrum: 0.3754260891582817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8226977882441133
  lightness: 0.25574943725951016
  saturation: 0.16995211644098163
  rhythmicContrast: 0.03688695281744003
purpose: []
